packages:
  - 'packages/*'

# Catalog for shared dependencies across workspace
catalog:
  # Core dependencies
  typescript: ^5.2.2
  '@types/node': ^20.8.0
  
  # Framework dependencies
  react: ^18.2.0
  '@types/react': ^18.2.25
  '@types/react-dom': ^18.2.11
  next: ^14.0.0
  
  # Build tools
  tsup: ^7.2.0
  unbuild: ^2.0.0
  rollup: ^4.0.0
  vite: ^4.5.0
  
  # Testing
  vitest: ^0.34.0
  '@testing-library/react': ^13.4.0
  '@testing-library/jest-dom': ^6.1.4
  jsdom: ^22.1.0
  
  # Linting and formatting
  eslint: ^8.50.0
  prettier: ^3.0.3
  '@typescript-eslint/eslint-plugin': ^6.7.4
  '@typescript-eslint/parser': ^6.7.4
  
  # Utilities
  zod: ^3.22.4
  axios: ^1.5.0
  lodash: ^4.17.21
  '@types/lodash': ^4.14.199
  
  # Date/time
  date-fns: ^2.30.0
  
  # Monitoring and observability
  '@opentelemetry/api': ^1.6.0
  '@opentelemetry/auto-instrumentations-node': ^0.40.0
  prom-client: ^15.0.0
  
  # Database
  prisma: ^5.4.2
  '@prisma/client': ^5.4.2
  
  # Server
  fastify: ^4.24.0
  '@fastify/cors': ^8.4.0
  '@fastify/helmet': ^11.1.1
  
  # React Native
  'react-native': ^0.72.0
  '@types/react-native': ^0.72.0